name: EmeraldMarket
main: com.flashofsilver.emeraldmarket.EmeraldMarket
version: 0.2
depend: [Vault, Questioner]
softdepend: [WorldGuard]
commands:
   emeraldmarket:
      description: Base EM command
      usage: /emeraldmarket [buy/sell] [price] [number]
      permission: emeraldmarket.basic.*
      permission-message: You don't have permission to use this.
      aliases: [em]
   emeraldmarketbuy:
      description: EM - Buy emeralds from the open market
      usage: /emeraldmarketbuy [price] [number]
      permission: emeraldmarket.basic.takeoffer
      permission-message: You don't have permission to buy emeralds.
      aliases: [emb]      
   emeraldmarketbuyaccept:
      description: EM - Buy emeralds by accepting a sell offer.
      usage: /emeraldmarketbuy [price] [number]
      permission: emeraldmarket.basic.takeoffer
      permission-message: You don't have permission to buy emeralds via offers.
      aliases: [emba]      
   emeraldmarketsell:
      description: EM - Sell emeralds from the open market
      usage: /emeraldmarketsell [price] [number]
      permission: emeraldmarket.basic.makeoffer
      permission-message: You don't have permission to sell emeralds.
      aliases: [ems]      
   emeraldmarketsellaccept:
      description: EM - Sell emeralds by accepting a buy offer.
      usage: /emeraldmarketsellaccept [price] [number]
      permission: emeraldmarket.basic.makeoffer
      permission-message: You don't have permission to sell emeralds via offers.
      aliases: [emsa]
   emeraldmarketadmin:
      description: EM - Admin settings
      usage: /emeraldmarketadmin setalias [username] [alias]
      permission: emeraldmarket.admin.settings
      permission-message: You don't have permission to administrate the market.
      aliases: [ema]
permissions:
    emeraldmarket.*:
        description: Gives access to all emerald market commands
        children:
            emeraldmarket.basic: true
            emeraldmarket.admin: true
            
    emeraldmarket.basic.*:
        description: Allows you to buy and sell on the emerald market
        default: true
        children:
            emeraldmarket.basic.buy: true
            emeraldmarket.basic.sell: true
            
    emeraldmarket.basic.buy.*:
        description: Allows you to make buy offers and take sell offers.
        default: true
        children:
            emeraldmarket.basic.buy.makebuyoffer: true
            emeraldmarket.basic.buy.takeselloffer: true
    emeraldmarket.basic.buy.makeoffer:
        description: Allows you to make buy offers.
        default: true
    emeraldmarket.basic.buy.takeselloffer:
        description: Allows you to take sell offers.
        default: true
    emeraldmarket.basic.sell.*:
        description: Allows you to make sell offers and take buy offers.
        default: true
        children:
            emeraldmarket.basic.sell.makeselloffer: true
            emeraldmarket.basic.sell.takebuyoffer: true
    emeraldmarket.basic.sell.makeselloffer:
        description: Allows you to make sell offers.
        default: true
    emeraldmarket.basic.sell.takebuyoffer:
        description: Allows you to take buy offers.
        default: true    
    emeraldmarket.admin.*:
        default: op
        description: Allows use of all admin commands
        children:
            emeraldmarket.admin.offers: true
            emeraldmarket.admin.settings: true
            emeraldmarket.admin.bypass: true
    emeraldmarket.admin.offers:
        default: op
        description: Allows market administration (endless offers, for instance)
    emeraldmarket.admin.settings:
        default: op
        description: Allows editing, saving and reloading of the configuration
    emeraldmarket.admin.bypass:
        default: op
        description: User can use EM without being in a WorldGuard region with emeraldmarket:allow
            